# Generated by Django 2.2.4 on 2021-03-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='disc_price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='org_price',
            field=models.CharField(max_length=10),
        ),
    ]
