# Generated by Django 2.2.4 on 2021-04-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='size',
            field=models.CharField(choices=[('XL', 'xl'), ('2XL', '2xl'), ('3XL', '3xl')], default='XL', max_length=4),
        ),
    ]
