# Generated by Django 2.2.4 on 2021-04-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_search_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='disc_price',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='org_price',
            field=models.FloatField(max_length=10),
        ),
    ]
