# Generated by Django 2.2.4 on 2021-04-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210407_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='brand',
            field=models.CharField(choices=[('superdry', 'superdry'), ('diesel', 'diesel'), ('napapijri', 'napapijri')], default='superdry', max_length=20),
        ),
        migrations.AddField(
            model_name='search',
            name='sex',
            field=models.CharField(choices=[('MAN', 'Мъже'), ('WOMEN', 'Жени')], default='S', max_length=10),
        ),
        migrations.AlterField(
            model_name='search',
            name='size',
            field=models.CharField(choices=[('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl'), ('2XL', '2xl'), ('3XL', '3xl')], default='S', max_length=4),
        ),
    ]
