# Generated by Django 2.2.4 on 2021-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210408_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='sex',
            field=models.CharField(choices=[('МЪЖЕ', 'Мъже'), ('ЖЕНИ', 'Жени')], default='S', max_length=10),
        ),
    ]
