# Generated by Django 2.2.4 on 2021-04-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210408_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='url',
        ),
        migrations.AlterField(
            model_name='search',
            name='sex',
            field=models.CharField(choices=[('Мъже', 'МЪЖЕ'), ('Жени', 'ЖЕНИ')], default='S', max_length=10),
        ),
    ]
