# Generated by Django 2.2.4 on 2021-04-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210408_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='clothes_type',
            field=models.CharField(choices=[('%D0%94%D1%80%D0%B5%D1%85%D0%B8-%D0%A2%D0%95%D0%9D%D0%98%D0%A1%D0%9A%D0%98', 'Тениски'), ('%D0%94%D1%80%D0%B5%D1%85%D0%B8-%D0%A1%D1%83%D0%B8%D1%82%D1%88%D1%8A%D1%80%D1%82%D0%B8_%D1%81_%D0%BA%D0%B0%D1%87%D1%83%D0%BB%D0%BA%D0%B0', 'Суитшърти'), ('%D0%94%D1%80%D0%B5%D1%85%D0%B8-%D0%91%D0%BB%D1%83%D0%B7%D0%B8', 'Блузи'), ('%D0%94%D1%80%D0%B5%D1%85%D0%B8-%D0%AF%D0%BA%D0%B5%D1%82%D0%B0', 'Якета')], default='%D0%94%D1%80%D0%B5%D1%85%D0%B8-%D0%A2%D0%95%D0%9D%D0%98%D0%A1%D0%9A%D0%98', max_length=500),
        ),
        migrations.AlterField(
            model_name='search',
            name='brand',
            field=models.CharField(choices=[('superdry', 'Superdry'), ('diesel', 'Diesel'), ('napapijri', 'Napapijri')], default='superdry', max_length=50),
        ),
        migrations.AlterField(
            model_name='search',
            name='sex',
            field=models.CharField(choices=[('%D0%9C%D1%8A%D0%B6%D0%B5', 'МЪЖЕ'), ('%D0%96%D0%B5%D0%BD%D0%B8', 'ЖЕНИ')], default='S', max_length=50),
        ),
        migrations.AlterField(
            model_name='search',
            name='size',
            field=models.CharField(choices=[('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl'), ('2XL', '2xl'), ('3XL', '3xl')], default='S', max_length=50),
        ),
    ]
