# Generated by Django 2.2.4 on 2021-04-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210408_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.AlterField(
            model_name='search',
            name='clothes_type',
            field=models.CharField(choices=[('T-shirts', 'Тениски'), ('Hoodies', 'Суитшърти'), ('Tops', 'Блузи'), ('Jackets', 'Якета')], default='T-shirts', max_length=500),
        ),
        migrations.AlterField(
            model_name='search',
            name='sex',
            field=models.CharField(choices=[('Man', 'МЪЖЕ'), ('Women', 'ЖЕНИ')], default='S', max_length=50),
        ),
    ]
