# Generated by Django 2.2.4 on 2021-04-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_shoessearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=300)),
                ('pic', models.CharField(max_length=300)),
                ('disc_price', models.FloatField(max_length=10)),
                ('org_price', models.FloatField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='clothessearch',
            name='sex',
            field=models.CharField(choices=[('Man', 'МЪЖЕ'), ('Women', 'ЖЕНИ')], default='Man', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoessearch',
            name='brand',
            field=models.CharField(choices=[('superdry', 'Superdry'), ('diesel', 'Diesel'), ('adidas', 'Adidas'), ('napapijri', 'Napapijri')], default='adidas', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoessearch',
            name='sex',
            field=models.CharField(choices=[('Man', 'МЪЖЕ'), ('Women', 'ЖЕНИ')], default='Man', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoessearch',
            name='size',
            field=models.CharField(choices=[('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl'), ('2XL', '2xl'), ('3XL', '3xl')], default='35', max_length=50),
        ),
    ]
